when:
  event: push

steps:
  build:
    image: golang
    environment:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
      GOCACHE: /ci-cache/go-build
      GOMODCACHE: /ci-cache/go-modules
    volumes:
      - ci-cache:/ci-cache
    commands:
      - go mod download
      - go build -ldflags="-s -w"

  publish:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: forgejo.pod.hetmer.net
      repo: ${CI_REPO_OWNER,,}/${CI_REPO_NAME,,}
      tags:
        - latest
        - ${CI_COMMIT_SHA:0:8}
      insecure: true
      insecure-registry: forgejo.pod.hetmer.net
      username: ${CI_REPO_OWNER}
      cache: true
      cache-repo: forgejo.pod.hetmer.net/toto/kaniko-cache
      password:
        from_secret: forgejo_token
    when:
      branch: master