when:
  - event: push

steps:
  build_and_publish_docker:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: forgejo.pod.hetmer.net/${CI_REPO_OWNER}/${CI_REPO_NAME}
      registry: forgejo.pod.hetmer.net
      insecure: true
      tags:
        - latest
        - ${CI_COMMIT_TAG##v}