when:
  - event: push

volumes:
  - name: ci-cache
    path: /cache

steps:
  build:
    image: golang
    environment:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
      GOCACHE: /cache/gocache
      GOMODCACHE: /cache/gomod
    volumes:
      - name: ci-cache
        path: /cache
    commands:
      - go env # just for debug~ senpai can remove it later~
      - go get
      - go build -ldflags="-s -w"

  publish:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: forgejo.pod.hetmer.net
      repo: ${CI_REPO_OWNER,,}/${CI_REPO_NAME,,}
      tags:
        - latest
        - ${CI_COMMIT_SHA:0:8}
      insecure: true
      insecure-registry: forgejo.pod.hetmer.net
      username: ${CI_REPO_OWNER}
      password:
        from_secret: forgejo_token
    when:
      branch: master
