when:
  - event: push

steps:
  build:
    image: docker
    commands:
      - docker login forgejo.pod.hetmer.net -u toto -p $DOCKER_PASSWORD 
      - docker build -t forgejo.pod.hetmer.net/toto/dns_fwd:latest .
      - docker push forgejo.pod.hetmer.net/toto/dns_fwd:latest