when:
  event: push

steps:
  build:
    image: golang
    environment:
      GOOS: linux
      GOARCH: amd64
      GOCACHE: /ci-cache/go-build
      GOMODCACHE: /ci-cache/go-modules
    volumes:
      - ci-cache:/ci-cache
    commands:
      - go mod download
      - go build -ldflags="-s -w"

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: ${CI_REPO_OWNER,,}/${CI_REPO_NAME,,}
      tags:
        - latest
      registry: forgejo.pod.hetmer.net
      username: ${CI_REPO_OWNER}
      password:
        from_secret: forgejo_token
      buildkit_config: |
        [registry."forgejo.pod.hetmer.net"]
          insecure = true
    when:
      branch: master