when:
  - event: push

steps:
  build:
    image: docker
    commands:
      - env
      - docker build -t forgejo.pod.hetmer.net/toto/dns_fwd:latest .
      - docker push forgejo.pod.hetmer.net/toto/dns_fwd:latest