when:
  event: push

steps:
  build:
    image: golang
    environment:
      GOOS: linux
      GOARCH: amd64
      GOCACHE: /ci-cache/go-build
      GOMODCACHE: /ci-cache/go-modules
    volumes:
      - ci-cache:/ci-cache
    commands:
      - go mod download
      - go build -ldflags="-s -w"

  container:
    image: docker.io/taywee/woodpecker-buildah:latest
    privileged: true
    volumes:
      - ci-cache:/var/lib/containers/storage
      - /etc/containers/registries.conf.d/:/etc/containers/registries.conf.d/
    settings:
      tag: forgejo.pod.hetmer.net/${CI_REPO_OWNER}/${CI_REPO_NAME}:latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: forgejo_token
      registry: forgejo.pod.hetmer.net