name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  create:

jobs:
  build-and-push:
    runs-on: docker
    container: catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Push Podman image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.GITHUB_REPOSITORY }}
          tags: latest
          registry: forgejo.pod.hetmer.net
          username: ${{ env.GITHUB_REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}