when:
  event: [push, manual]
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  build:
    image: golang
    environment:
      GOOS: linux
      GOARCH: amd64
      GOCACHE: /ci-cache/go-build
      GOMODCACHE: /ci-cache/go-modules
    commands:
      - go mod download
      - go build -ldflags="-s -w"

  container:
    image: quay.io/buildah/stable:latest
    privileged: true
    environment:
      PASSWORD:
        from_secret: forgejo_token
    commands:
      - export REGISTRY=forgejo.pod.hetmer.net
      - export IMAGE=$REGISTRY/${CI_REPO_OWNER}/${CI_REPO_NAME}:latest
      - buildah login -u "${CI_REPO_OWNER}" -p "$PASSWORD" $REGISTRY
      - buildah bud -t $IMAGE .
      - buildah push $IMAGE
